### ISSUE TITLE
关于model save

### ISSUE THREAD

**Issue by Caojunkai** [lijy91/daza-backend#2]
你好，在user表中有些字段设置为NOT NULL 并且没有默认值,在注册时这些字段并没有赋值却可以插入成功，没有出现doesn't have a default value的错误？谢谢

**Comment by lijy91** [comment]
如果通过 Laravel Eloquent模块去保存的数据，框架会自动将这些值设置为`空字符`而非`NULL`，面如果通过DB类来保存的数据就会出现这种错误。

抱歉这么久才回答。
