### ISSUE TITLE
如何通过API来返回中文或者英文（多语言）

### ISSUE THREAD

**Issue by ucoker** [lijy91/daza-backend#4]
在`resources\lang`下有`en`和`zh-CN`，  
假设客户端分中文版本跟英文版本，如何告诉laravel来返回正确的语言？

```
$this->failure(trans('jwt.could_not_create_token'), 500);
```

**Comment by lijy91** [comment]
可以参考下面这个配置，daza这个项目并没有做多语言切换
```
Route::get('welcome/{locale}', function ($locale) {
    App::setLocale($locale);

    //
});
```

https://laravel-china.org/docs/5.3/localization#overriding-package-language-files

**Comment by ucoker** [comment]
官方这个，我有查看到。  
只能在地址栏来区分是`en`还是`zh-CN`吗？  
这样API的地址好像有点多，不清楚能不能加在`header`或者其他地方，来告诉`laravel`

**Comment by lijy91** [comment]
你可以用中间键来做
